-- ==============================================================================
-- RUMI-SYNC — SETUP DATABASE SUPABASE (V2)
-- Jalankan di SQL Editor Supabase. Klik tombol "RUN".
-- ==============================================================================

-- ⚠️ HAPUS TABEL LAMA (jika upgrade dari V1). Komentar baris ini jika tidak ingin menghapus data.
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS sensor_data CASCADE;
DROP TABLE IF EXISTS feed_records CASCADE;
DROP TABLE IF EXISTS esp_status CASCADE;
DROP TABLE IF EXISTS rel_config CASCADE;
DROP TABLE IF EXISTS cattle_inventory CASCADE;

-- 1. TABEL INVENTARIS SAPI
CREATE TABLE cattle_inventory (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  gender TEXT,
  breed TEXT,
  age_year INTEGER,
  age_month INTEGER,
  age_day INTEGER,
  current_temp NUMERIC DEFAULT 0,
  current_chewing INTEGER DEFAULT 0,
  current_rssi INTEGER DEFAULT NULL,    -- RSSI sinyal BLE dari iTag (dikirim ESP)
  health_score INTEGER DEFAULT 100,     -- Skor kesehatan global (0-100, dihitung backend)
  health_status TEXT DEFAULT 'Aman',
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABEL HISTORI SENSOR (suhu, kunyahan, rssi per waktu)
CREATE TABLE sensor_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cattle_id TEXT REFERENCES cattle_inventory(id) ON DELETE CASCADE,
  temperature NUMERIC NOT NULL,
  chewing_rate INTEGER NOT NULL,
  rssi INTEGER DEFAULT NULL,
  status TEXT,
  recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABEL NOTIFIKASI
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cattle_id TEXT REFERENCES cattle_inventory(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'warning',
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. TABEL STATUS ESP (baterai global, bukan per sapi)
CREATE TABLE esp_status (
  id TEXT PRIMARY KEY DEFAULT 'main',
  battery INTEGER DEFAULT 100,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. TABEL CATATAN PAKAN (tersimpan hanya saat peternak menerapkan)
CREATE TABLE feed_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cattle_id TEXT REFERENCES cattle_inventory(id) ON DELETE CASCADE,
  serat_id TEXT,
  pati_id TEXT,
  protein_id TEXT,
  ratio_serat INTEGER,
  booster_id TEXT,
  methane_estimate INTEGER,
  dmi NUMERIC,
  applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. TABEL KONFIGURASI REL (berapa sapi per rel)
CREATE TABLE rel_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rel_number INTEGER UNIQUE NOT NULL,
  cattle_count INTEGER DEFAULT 10,
  label TEXT
);

-- Data awal ESP
INSERT INTO esp_status (id, battery) VALUES ('main', 100) ON CONFLICT (id) DO NOTHING;

-- Data awal konfigurasi rel (3 rel default, masing-masing 10 sapi)
INSERT INTO rel_config (rel_number, cattle_count, label) VALUES (1, 10, 'Rel 1') ON CONFLICT (rel_number) DO NOTHING;
INSERT INTO rel_config (rel_number, cattle_count, label) VALUES (2, 10, 'Rel 2') ON CONFLICT (rel_number) DO NOTHING;
INSERT INTO rel_config (rel_number, cattle_count, label) VALUES (3, 10, 'Rel 3') ON CONFLICT (rel_number) DO NOTHING;

-- ==============================================================================
-- AKTIFKAN REALTIME
-- ==============================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE sensor_data;
ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE cattle_inventory;
ALTER PUBLICATION supabase_realtime ADD TABLE esp_status;
ALTER PUBLICATION supabase_realtime ADD TABLE feed_records;
ALTER PUBLICATION supabase_realtime ADD TABLE rel_config;

-- ==============================================================================
-- DUMMY DATA (Opsional)
-- ==============================================================================
INSERT INTO cattle_inventory (id, name, gender, breed, age_year, age_month, age_day)
VALUES
  ('ID-001', 'Brahman Star', 'Jantan', 'Brahman Cross', 3, 2, 10),
  ('ID-002', 'Limosin Queen', 'Betina', 'Limosin', 2, 5, 12)
ON CONFLICT (id) DO NOTHING;
