-- ==============================================================================
-- PANDUAN SETUP SUPABASE (Sangat Mudah Dipahami)
-- Copy semua teks di bawah ini dan paste ke SQL Editor di dashboard Supabase Anda.
-- Lalu klik tombol "RUN" (Jalankan).
-- ==============================================================================

-- 1. TABEL INVENTARIS SAPI (Menyimpan data induk setiap sapi)
CREATE TABLE IF NOT EXISTS cattle_inventory (
  id TEXT PRIMARY KEY, -- Contoh: "ID-002"
  name TEXT NOT NULL,
  gender TEXT,
  breed TEXT,
  age_year INTEGER,
  age_month INTEGER,
  age_day INTEGER,
  current_temp NUMERIC DEFAULT 0,
  current_chewing INTEGER DEFAULT 0,
  battery INTEGER DEFAULT 100,
  health_status TEXT DEFAULT 'Aman',
  last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. TABEL HISTORI SENSOR (Menyimpan riwayat suhu dan kunyahan dari waktu ke waktu)
CREATE TABLE IF NOT EXISTS sensor_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cattle_id TEXT REFERENCES cattle_inventory(id) ON DELETE CASCADE,
  temperature NUMERIC NOT NULL,
  chewing_rate INTEGER NOT NULL,
  battery_level INTEGER,
  status TEXT, -- 'normal' atau 'danger'
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. TABEL NOTIFIKASI (Menyimpan peringatan atau anomali penyakit)
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cattle_id TEXT REFERENCES cattle_inventory(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'warning', -- 'warning', 'danger', 'success'
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- MENGAKTIFKAN FITUR REALTIME UNTUK APLIKASI WEB
-- (Wajib dijalankan agar grafik dan toast notifikasi bergerak tanpa di-refresh)
-- ==============================================================================
alter publication supabase_realtime add table sensor_data;
alter publication supabase_realtime add table notifications;
alter publication supabase_realtime add table cattle_inventory;

-- ==============================================================================
-- DUMMY DATA AWAL (Opsional, hanya untuk mengetes apakah aplikasi sudah konek)
-- ==============================================================================
INSERT INTO cattle_inventory (id, name, gender, breed, age_year, age_month, age_day) 
VALUES 
  ('ID-001', 'Brahman Star', 'Jantan', 'Brahman Cross', 3, 2, 10),
  ('ID-002', 'Limosin Queen', 'Betina', 'Limosin', 2, 5, 12)
ON CONFLICT (id) DO NOTHING;
